name: test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: >-
          deno test
          --doc
          --coverage=.cov
      - run: deno coverage --lcov .cov > .cov.lcov
      - uses: codecov/codecov-action@v2
        with:
          files: .cov.lcov
          env_vars: OS

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint
      - run: deno fmt --check --ignore=.vscode/
